services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    environment:
      EULA: "true"
      TYPE: "PAPER"
      DIFFICULTY: normal
      MODE: survival
      HARDCORE:  FALSE
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      WHITELIST: |
        02ceebcc-1b0d-403d-bf5d-65d1a3a767d3
        8b618607-d722-4d93-8a41-40c209c22339
      MEMORY: 6G

    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ./data:/data
